### PR TITLE
Put Google Maps API on website

### PR DESCRIPTION
**Pull request by jachen20**
#35 

Here's a screenshot of what the website looks like:
uitraffic map
The orange shaded area is where the "markers" are.

### CODE REVIEW

**Comment by bplin2** [comment]
Is the error fixed/should I review this?

**Comment by jachen20** [comment]
> Is the error fixed/should I review this?

Yep the error's fixed, so there's no need to review this!

**Comment by bplin2** [comment]
> > Is the error fixed/should I review this?
> 
> Yep the error's fixed, so there's no need to review this!

I gotta review it so that you can merge to master. Can you make the commit message a little clearer next time if an implementation works or not? ex. "fixed _____ error" or "still working on fixing _______"

**Comment by jachen20** [comment]
> > > Is the error fixed/should I review this?
> > 
> > 
> > Yep the error's fixed, so there's no need to review this!
> 
> I gotta review it so that you can merge to master. Can you make the commit message a little clearer next time if an implementation works or not? ex. "fixed _____ error" or "still working on fixing _______"

Alright I'll definitely make sure to do that! These changes don't have to be merged because Matthew's PR which was approved earlier has the full workable version of what I was working on.

**Comment by annie-qiu26** [comment]
just approved!

**Pull request merged**
